name: 'Post to Fediverse'
description: 'A GitHub Action to post a message to a Fediverse instance.'
inputs:
  access_token:
    description: 'The access token for the Fediverse instance.'
    required: true
  host_name:
    description: 'The host name of the Fediverse instance.'
    required: true
  api_path:
    description: 'The API path for posting a status. Defaults to /api/v1/statuses'
    required: false
    default: '/api/v1/statuses'
  message:
    description: 'The content of the message to post.'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'message-square'
  color: 'blue'
